### ISSUE TITLE
Last minute checklist

### ISSUE THREAD

**Issue by richardltyler** [richardltyler/A2B#32]
- [x] everything is tested and all .only's are gone
- [x] all commented code is gone 
- [x] responsive 
- [x] try to break it and make issues for those bugs
